# Generated by Django 5.0 on 2024-01-07 14:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reactivos', '0003_producto_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='producto',
            name='sedronar',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='producto',
            name='imagen',
            field=models.ImageField(blank=True, null=True, upload_to='reactivos'),
        ),
    ]
