# Generated by Django 5.0 on 2024-01-11 12:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reactivos', '0005_producto_descarte'),
    ]

    operations = [
        migrations.AddField(
            model_name='producto',
            name='ubicacion',
            field=models.CharField(default='Armario Amarillo N°2', max_length=50),
        ),
    ]
