# Generated by Django 5.0 on 2024-01-14 12:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reactivos', '0006_producto_ubicacion'),
    ]

    operations = [
        migrations.AlterField(
            model_name='producto',
            name='numero',
            field=models.IntegerField(default=1),
        ),
    ]
