# Generated by Django 5.0 on 2024-01-14 12:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reactivos', '0007_alter_producto_numero'),
    ]

    operations = [
        migrations.RenameField(
            model_name='producto',
            old_name='numero',
            new_name='unidades',
        ),
    ]
