# Generated by Django 5.0 on 2024-01-14 15:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reactivos', '0008_rename_numero_producto_unidades'),
    ]

    operations = [
        migrations.AlterField(
            model_name='producto',
            name='descarte',
            field=models.TextField(default='Este reactivo debe descartarse como:'),
        ),
    ]
