# Generated by Django 5.0 on 2024-01-02 15:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('equipamiento', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='imagen',
            field=models.ImageField(blank=True, null=True, upload_to='fotos'),
        ),
        migrations.AlterField(
            model_name='post',
            name='manual',
            field=models.FileField(blank=True, null=True, upload_to='pdfs'),
        ),
    ]
