# Generated by Django 5.0 on 2024-01-07 16:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('equipamiento', '0003_alter_post_imagen_alter_post_manual'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='ubicación',
            new_name='responsable',
        ),
        migrations.AddField(
            model_name='post',
            name='ubicacion',
            field=models.CharField(default='exit', max_length=50),
            preserve_default=False,
        ),
    ]
