# Generated by Django 5.0 on 2024-01-11 16:34

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('equipamiento', '0005_post_poe'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Post',
            new_name='Equipamiento',
        ),
        migrations.AlterModelOptions(
            name='equipamiento',
            options={'verbose_name': 'equipamiento', 'verbose_name_plural': 'equipamientos'},
        ),
    ]
