# Generated by Django 5.0 on 2024-01-11 17:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('equipamiento', '0006_rename_post_equipamiento_alter_equipamiento_options'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='equipamiento',
            name='categorias',
        ),
        migrations.RemoveField(
            model_name='equipamiento',
            name='autor_creacion',
        ),
        migrations.RemoveField(
            model_name='equipamiento',
            name='autor_ultima_edicion',
        ),
        migrations.DeleteModel(
            name='Categoria',
        ),
        migrations.AddField(
            model_name='equipamiento',
            name='categorias',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
