# Generated by Django 5.0 on 2024-01-12 23:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('equipamiento', '0007_remove_equipamiento_categorias_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='equipamiento',
            name='categorias',
            field=models.CharField(blank=True, choices=[('electroquimico', 'Equipamiento Electroquímico'), ('general', 'Equipamiento General')], max_length=50, null=True),
        ),
    ]
